Fix depup
`depup` workflow has been failing due to the following error.

ref: https://github.com/reviewdog/action-rubocop/runs/2202571963?check_suite_focus=true

```
Error: Unable to process command '::set-env name=pythonLocation::/opt/hostedtoolcache/Python/3.9.2/x64' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/opt/hostedtoolcache/Python/3.9.2/x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/opt/hostedtoolcache/Python/3.9.2/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

This error occurs with `peter-evans/create-pull-request@v2` that uses
deprecated `set-env` in its process.
ref: https://github.com/peter-evans/create-pull-request/issues/632

So it should be upgraded to v3 to avoid the failure.
upgrade guide: https://github.com/peter-evans/create-pull-request/blob/5666cd8fe97f4f0781e50095d9e853a7a97e238b/docs/updating.md